<?php
return [
  [
    'name' => 'OptionGroup_case_status_OptionValue_Requested',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'case_status',
        'label' => 'Requested',
        'value' => '6',
        'name' => 'Requested',
        'grouping' => 'Opened',
        'filter' => 0,
        'is_default' => FALSE,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
        'icon' => NULL,
        'color' => '#1100ff',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_case_status_OptionValue_Active',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'case_status',
        'label' => 'Active',
        'value' => '7',
        'name' => 'Active',
        'grouping' => 'Opened',
        'filter' => 0,
        'is_default' => FALSE,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
        'icon' => NULL,
        'color' => '#00ff33',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_case_status_OptionValue_Passive',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'case_status',
        'label' => 'Passive',
        'value' => '8',
        'name' => 'Passive',
        'grouping' => 'Opened',
        'filter' => 0,
        'is_default' => FALSE,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
        'icon' => NULL,
        'color' => '#fbff00',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_case_status_OptionValue_Prospect',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'case_status',
        'label' => 'Prospect',
        'value' => '10',
        'name' => 'Prospect',
        'grouping' => 'Opened',
        'filter' => 0,
        'is_default' => FALSE,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
        'icon' => NULL,
        'color' => '#bdbdbd',
      ],
    ],
  ],
];
