<?php
use CRM_DdVenueManager_ExtensionUtil as E;

return [
  [
    'name' => 'RelationshipType_Venue_Officer',
    'entity' => 'RelationshipType',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name_a_b' => 'is venue officer for',
        'label_a_b' => 'is venue officer for',
        'name_b_a' => 'has venue officer',
        'label_b_a' => 'has venue officer',
        'description' => NULL,
        'contact_type_a' => 'Individual',
        'contact_type_b' => 'Organization',
        'contact_sub_type_a' => NULL,
        'contact_sub_type_b' => 'Venue',
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'relationship_block.is_relationship_block_on_summary' => NULL,
        'relationship_block.relationship_block_exclude_expired' => NULL,
        'relationship_block.relationship_block_exclude_pending' => NULL,
      ],
    ],
  ],
  [
    'name' => 'RelationshipType_Venue_Coordinator',
    'entity' => 'RelationshipType',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name_a_b' => 'is coordinator for',
        'label_a_b' => 'is coordinator for',
        'name_b_a' => 'has coordinator',
        'label_b_a' => 'has coordinator',
        'description' => NULL,
        'contact_type_a' => 'Individual',
        'contact_type_b' => 'Organization',
        'contact_sub_type_a' => NULL,
        'contact_sub_type_b' => 'Venue',
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'relationship_block.is_relationship_block_on_summary' => NULL,
        'relationship_block.relationship_block_exclude_expired' => NULL,
        'relationship_block.relationship_block_exclude_pending' => NULL,
      ],
    ],
  ],
  [
    'name' => 'RelationshipType_Venue_Contact_Person',
    'entity' => 'RelationshipType',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name_a_b' => 'venue contact person',
        'label_a_b' => 'venue contact person',
        'name_b_a' => 'venue contact person',
        'label_b_a' => 'venue contact person',
        'description' => NULL,
        'contact_type_a' => 'Individual',
        'contact_type_b' => 'Organization',
        'contact_sub_type_a' => 'Venue_Contact_Person',
        'contact_sub_type_b' => 'Venue',
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'relationship_block.is_relationship_block_on_summary' => FALSE,
        'relationship_block.relationship_block_exclude_expired' => TRUE,
        'relationship_block.relationship_block_exclude_pending' => FALSE,
      ],
    ],
  ],
];
