<?php
return [
  [
    'name' => 'UFGroup_Venue_Summary',
    'entity' => 'UFGroup',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'is_active' => TRUE,
        'group_type' => [
          'Organization',
          'Venue',
        ],
        'title' => 'Venue Summary',
        'frontend_title' => NULL,
        'description' => NULL,
        'help_pre' => NULL,
        'help_post' => NULL,
        'limit_listings_group_id' => NULL,
        'post_URL' => NULL,
        'add_to_group_id' => NULL,
        'add_captcha' => FALSE,
        'is_map' => FALSE,
        'is_edit_link' => FALSE,
        'is_uf_link' => FALSE,
        'is_update_dupe' => TRUE,
        'cancel_URL' => NULL,
        'is_cms_user' => FALSE,
        'notify' => NULL,
        'is_reserved' => FALSE,
        'name' => 'Venue_Summary',
        'is_proximity_search' => FALSE,
        'cancel_button_text' => NULL,
        'submit_button_text' => NULL,
        'add_cancel_button' => TRUE,
      ],
      'chain' => [
          'UFJoin' => [
            'UFJoin',
            'save',
            [
              'records' => [
                ['uf_group_id' => '$id', 'module' => 'Profile'],
              ],
              'match' => [
                'module',
                'uf_group_id',
              ],
            ]
          ],
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Summary_Organization_Name',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Summary',
        'field_name' => 'organization_name',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Organization Name',
        'field_type' => 'Organization',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Summary_Legal_Name',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Summary',
        'field_name' => 'legal_name',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Legal Name',
        'field_type' => 'Organization',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Summary_Venue_Type',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Summary',
        'field_name:name' => 'Venue_Summary.Venue_Type',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Venue Type',
        'field_type' => 'Venue',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Summary_Venue_Overview',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Summary',
        'field_name:name' => 'Venue_Summary.Venue_Overview',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Standplatz/Lager',
        'field_type' => 'Venue',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],

  [
    'name' => 'UFGroup_Venue_Summary_Request_Modality',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Summary',
        'field_name:name' => 'Venue_Summary.Request_Modality',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Request Modality',
        'field_type' => 'Venue',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Summary_Billing_and_Request_Modality',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Summary',
        'field_name:name' => 'Venue_Summary.Billing_and_Request_Modality',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Billing Modality',
        'field_type' => 'Venue',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Summary_Company_Overview',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Summary',
        'field_name:name' => 'Venue_Summary.Company_Overview',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Company Overview',
        'field_type' => 'Venue',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
];
