<?php
return [
  [
    'name' => 'UFGroup_Venue_Contact_Person',
    'entity' => 'UFGroup',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'is_active' => TRUE,
        'group_type' => [
          'Venue_Contact_Person',
          'Contact',
        ],
        'title' => 'Venue Contact Person',
        'frontend_title' => NULL,
        'description' => NULL,
        'help_pre' => NULL,
        'help_post' => NULL,
        'limit_listings_group_id' => NULL,
        'post_URL' => NULL,
        'add_to_group_id' => NULL,
        'add_captcha' => FALSE,
        'is_map' => FALSE,
        'is_edit_link' => FALSE,
        'is_uf_link' => FALSE,
        'is_update_dupe' => 2,
        'cancel_URL' => NULL,
        'is_cms_user' => FALSE,
        'notify' => NULL,
        'is_reserved' => FALSE,
        'name' => 'Venue_Contact_Person',
        'created_date' => NULL,
        'is_proximity_search' => FALSE,
        'cancel_button_text' => NULL,
        'submit_button_text' => NULL,
        'add_cancel_button' => TRUE,
      ],
      'chain' => [
        'UFJoin' => [
          'UFJoin',
          'save',
          [
            'records' => [
              ['uf_group_id' => '$id', 'module' => 'Profile'],
            ],
            'match' => [
              'module',
              'uf_group_id',
            ],
          ]
        ],
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Contact_Person_Prefix_Id',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Contact_Person',
        'field_name' => 'prefix_id',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Prefix',
        'field_type' => 'Venue_Contact_Person',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Contact_Person_Formal_Title',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Contact_Person',
        'field_name' => 'formal_title',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Formal Title',
        'field_type' => 'Venue_Contact_Person',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Contact_Person_First_Name',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Contact_Person',
        'field_name' => 'first_name',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'First Name',
        'field_type' => 'Venue_Contact_Person',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Contact_Person_Last_Name',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Contact_Person',
        'field_name' => 'last_name',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => TRUE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Last Name',
        'field_type' => 'Venue_Contact_Person',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Contact_Person_Postfix_Title',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Contact_Person',
        'field_name:name' => 'Individual_Details.Postfix_Title',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Postfix Title',
        'field_type' => 'Individual',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Contact_Person_Email',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Contact_Person',
        'field_name' => 'email',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => NULL,
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id' => NULL,
        'website_type_id' => NULL,
        'label' => 'Email',
        'field_type' => 'Contact',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'UFGroup_Venue_Contact_Person_Phone',
    'entity' => 'UFField',
    'cleanup' => 'never',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'uf_group_id.name' => 'Venue_Contact_Person',
        'field_name' => 'phone',
        'is_active' => TRUE,
        'is_view' => FALSE,
        'is_required' => FALSE,
        'help_post' => '<strong>Wichtig:</strong> Die Postadresse der Kontaktperson muss im Anschluss in der Kontaktansicht manuell ergänzt werden!',
        'help_pre' => NULL,
        'visibility' => 'User and User Admin Only',
        'in_selector' => FALSE,
        'is_searchable' => FALSE,
        'location_type_id' => NULL,
        'phone_type_id:name' => 'Phone',
        'website_type_id' => NULL,
        'label' => 'Phone',
        'field_type' => 'Contact',
        'is_reserved' => FALSE,
        'is_multi_summary' => FALSE,
      ],
    ],
  ],
];
