<?php
return [
  [
    'name' => 'SavedSearch_Scheduled_Venue_Activities',
    'entity' => 'SavedSearch',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Scheduled_Venue_Activities',
        'label' => 'Venue Scheduled Activities',
        'form_values' => NULL,
        'mapping_id' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'Activity',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'subject',
            'GROUP_CONCAT(DISTINCT Activity_ActivityContact_Contact_01.display_name) AS GROUP_CONCAT_Activity_ActivityContact_Contact_01_display_name',
            'GROUP_CONCAT(DISTINCT Activity_ActivityContact_Contact_02.display_name) AS GROUP_CONCAT_Activity_ActivityContact_Contact_02_display_name',
            'GROUP_CONCAT(DISTINCT Activity_CaseActivity_Case_01_Case_CaseContact_Contact_01.display_name) AS GROUP_CONCAT_Activity_CaseActivity_Case_01_Case_CaseContact_Contact_01_display_name',
            'activity_date_time',
            'created_date',
            'status_id:label',
            'details',
            'activity_type_id:label',
            'Activity_ActivityContact_Contact_03.display_name',
          ],
          'orderBy' => [],
          'where' => [
            [
              'status_id:name',
              '=',
              'Scheduled',
            ],
          ],
          'groupBy' => [
            'id',
          ],
          'join' => [
            [
              'Case AS Activity_CaseActivity_Case_01',
              'INNER',
              'CaseActivity',
              [
                'id',
                '=',
                'Activity_CaseActivity_Case_01.activity_id',
              ],
              [
                'Activity_CaseActivity_Case_01.case_type_id:name',
                '=',
                '"Venue"',
              ],
            ],
            [
              'Contact AS Activity_ActivityContact_Contact_01',
              'LEFT',
              'ActivityContact',
              [
                'id',
                '=',
                'Activity_ActivityContact_Contact_01.activity_id',
              ],
              [
                'Activity_ActivityContact_Contact_01.record_type_id:name',
                '=',
                '"Activity Targets"',
              ],
            ],
            [
              'Contact AS Activity_ActivityContact_Contact_02',
              'LEFT',
              'ActivityContact',
              [
                'id',
                '=',
                'Activity_ActivityContact_Contact_02.activity_id',
              ],
              [
                'Activity_ActivityContact_Contact_02.record_type_id:name',
                '=',
                '"Activity Assignees"',
              ],
            ],
            [
              'Contact AS Activity_CaseActivity_Case_01_Case_CaseContact_Contact_01',
              'INNER',
              'CaseContact',
              [
                'Activity_CaseActivity_Case_01.id',
                '=',
                'Activity_CaseActivity_Case_01_Case_CaseContact_Contact_01.case_id',
              ],
            ],
            [
              'Contact AS Activity_ActivityContact_Contact_03',
              'LEFT',
              'ActivityContact',
              [
                'id',
                '=',
                'Activity_ActivityContact_Contact_03.activity_id',
              ],
              [
                'Activity_ActivityContact_Contact_03.record_type_id:name',
                '=',
                '"Activity Source"',
              ],
            ],
          ],
          'having' => [],
        ],
        'expires_date' => NULL,
        'description' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Scheduled_Venue_Activities_SearchDisplay_Scheduled_Venue_Activities_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Scheduled_Venue_Activities_Table',
        'label' => 'Venue Scheduled Activities Table',
        'saved_search_id.name' => 'Scheduled_Venue_Activities',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [
            [
              'activity_date_time',
              'ASC',
            ],
            [
              'created_date',
              'ASC',
            ],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Activity_ActivityContact_Contact_01_display_name',
              'dataType' => 'String',
              'label' => 'Venue / Contact Person',
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Activity_ActivityContact_Contact_01',
                'target' => '_blank',
              ],
              'title' => NULL,
            ],
            [
              'type' => 'field',
              'key' => 'activity_type_id:label',
              'dataType' => 'Integer',
              'label' => 'Activity Type',
              'sortable' => TRUE,
              'icons' => [
                [
                  'field' => 'activity_type_id:icon',
                  'side' => 'left',
                ],
              ],
              'rewrite' => '[activity_type_id:label]: [subject]',
              'title' => '[details]',
            ],
            [
              'type' => 'field',
              'key' => 'activity_date_time',
              'dataType' => 'Timestamp',
              'label' => 'Activity Date',
              'sortable' => TRUE,
              'cssRules' => [],
            ],
            [
              'type' => 'field',
              'key' => 'Activity_ActivityContact_Contact_03.display_name',
              'dataType' => 'String',
              'label' => 'Added By',
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'Activity_ActivityContact_Contact_03',
                'target' => '_blank',
              ],
              'title' => 'Created at [created_date]',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Activity_ActivityContact_Contact_02_display_name',
              'dataType' => 'String',
              'label' => 'Assignee',
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '_blank',
                  'icon' => 'fa-external-link',
                  'text' => 'Case',
                  'style' => 'success',
                  'path' => 'civicrm/contact/view/case?reset=1&id=[case_id]&cid=[Activity_CaseActivity_Case_01_Case_CaseContact_Contact_01.id]&action=view&context=case&selectedChild=case',
                  'condition' => [],
                ],
                [
                  'entity' => 'Activity',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => 'Edit',
                  'style' => 'info',
                  'path' => '',
                  'condition' => [],
                ],
                [
                  'entity' => 'Activity',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => 'Delete',
                  'style' => 'danger',
                  'path' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => [
            'table',
            'table-striped',
          ],
        ],
        'acl_bypass' => FALSE,
      ],
    ],
  ],
];
